#!/bin/sh

if [ $# -gt 0 ]; then
    current_time=`date '+%F_%H-%M-%S'`
    file_name="$1_${current_time}.tar.gz"

    shift
    params=" -c -a -v -f ${file_name} $@"
    echo "Filename: ${file_name}"
    echo "Tar params: ${params}"
    tar ${params}
fi
