#!/bin/sh

backup_dir=$HOME/Dropbox/Backup

if [ -z "$MAIL" ]; then
    echo '$MAIL variable is empty'
    return
fi

if [ $# -gt 0 ]; then
    current_time=`date '+%F_%H-%M-%S'`
    file_name="$1_${current_time}.tar.gz"

    shift
    params=" -c -a -v -f ${file_name} $@"
    echo "Filename: ${file_name}"
    echo "Tar params: ${params}"
    tar $params

    gpg --sign --encrypt -r "$MAIL" "$file_name"
    rm "$file_name"
    mv -v "${file_name}.gpg" "$backup_dir"
fi
